// Generated by CoffeeScript 1.4.0
(function() {
  var targ;

  targ = function(args, scheme) {
    var arg, i, item, j, keys, lenKeys, originalType, out, type;
    if (Object.prototype.toString.call(scheme) !== '[object Object]') {
      throw 'targ: wrong type';
    }
    out = {};
    keys = Object.keys(scheme);
    i = 0;
    j = 0;
    lenKeys = keys.length;
    while (j < lenKeys && i < lenKeys) {
      arg = args[j];
      item = scheme[keys[i]];
      if (!Array.isArray(item)) {
        item = [item];
      }
      type = item[0];
      if (typeof type !== 'string') {
        originalType = type;
        type = type.name;
      }
      if (Object.prototype.toString.call(arg) === '[object ' + type + ']' || (Object.prototype.toString.call(originalType) === '[object Function]' && arg instanceof originalType)) {
        out[keys[i]] = arg;
        i++;
        j++;
      } else {
        out[keys[i]] = item[1];
        i++;
      }
    }
    return out;
  };

  module.exports = targ;

}).call(this);
