// Generated by CoffeeScript 1.4.0
(function() {
  var targ;

  targ = require('./targ');

  module.exports = {
    simple: function(test) {
      var func;
      func = (function() {});
      (function(arg1, arg2, arg3) {
        var args;
        args = targ(arguments, {
          str: String,
          bool: Boolean,
          func: Function
        });
        return test.deepEqual(args, {
          str: 'string',
          bool: true,
          func: func
        });
      })('string', true, func);
      (function(arg1, arg2, arg3) {
        var args;
        args = targ(arguments, {
          str: [String, ''],
          bool: [Boolean, false],
          func: [Function, func]
        });
        return test.deepEqual(args, {
          str: '',
          bool: false,
          func: func
        });
      })(void 0, void 0, void 0);
      return test.done();
    },
    missingParam: function(test) {
      var func;
      func = (function() {});
      (function(arg1, arg2) {
        var args;
        args = targ(arguments, {
          str: String,
          obj: Object,
          func: Function
        });
        return test.deepEqual(args, {
          str: 'string',
          obj: void 0,
          func: func
        });
      })('string', func);
      return test.done();
    },
    extraParam: function(test) {
      var func;
      func = (function() {});
      (function(arg1, arg2, arg3, arg4) {
        var args;
        args = targ(arguments, {
          str: String,
          bool: Boolean,
          func: Function
        });
        return test.deepEqual(args, {
          str: 'string',
          bool: true,
          func: void 0
        });
      })('string', true, false, func);
      return test.done();
    },
    customClass: function(test) {
      var Type, func, obj;
      func = (function() {});
      Type = (function() {});
      obj = new Type;
      (function(arg1, arg2) {
        var args;
        args = targ(arguments, {
          obj: Type,
          func: Function
        });
        return test.deepEqual(args, {
          obj: obj,
          func: func
        });
      })(obj, func);
      (function(arg1, arg2) {
        var args;
        args = targ(arguments, {
          obj: Type,
          func: Function
        });
        return test.deepEqual(args, {
          obj: void 0,
          func: void 0
        });
      })({}, void 0);
      return test.done();
    }
  };

}).call(this);
